version: "3.9"

services:
  client:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # - .:/usr/app
      - /usr/app/node_modules
    # tty: true
    # stdin_open: true
    # command: ["sh"]


